sudo: required

dist: trusty

language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server
- docker

cache: pip

python:
- '3.6'

install:
- make install

script:
- make lint
- make test
- ./tests/end2end.sh

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
