version: '2'
services:
  logs:
    image: gliderlabs/logspout
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
    - './pgdata:/var/lib/postgresql/data/pgdata'
    restart: always
    depends_on:
    - logs

  redis:
    image: redis:3.0-alpine
    restart: always
    depends_on:
    - logs

  web:
    build: .
    environment:
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PASSWORD: docker
      APP_REDIS_HOST: redis
      BIND: 0.0.0.0:8000
      CHECK: web
    restart: always
    depends_on:
    - postgres
    - redis

  worker:
    build: .
    volumes:
    - ./media:/media
    entrypoint:
    - ./run.py
    - worker
    environment:
      APP_REDIS_HOST: redis
      APP_MEDIA: '/media'
      CHECK: worker
    restart: always
    depends_on:
    # currently doesn't use postgres
    - redis
