version: '2'

volumes:
 pg_data: {}
 media: {}
 redis_data: {}

services:
  logs:
    image: gliderlabs/logspout
    environment:
      SYSLOG_HOSTNAME: 'tcsocket'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
    - pg_data:/var/lib/postgresql/data
    restart: always
    depends_on:
    - logs

  redis:
    image: redis:3.0-alpine
    volumes:
    - redis_data:/data
    restart: always
    depends_on:
    - logs

  web:
    build: tcsocket
    environment:
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PASSWORD: docker
      APP_REDIS_HOST: redis
      APP_MASTER_KEY: ${APP_MASTER_KEY}
      BIND: 0.0.0.0:8000
      CHECK: web
      COMMIT: ${COMMIT}
      RELEASE_DATE: ${RELEASE_DATE}
      RAVEN_DSN: ${RAVEN_DSN}
    restart: always
    depends_on:
    - postgres
    - redis

  worker:
    build: tcsocket
    volumes:
    - media:/media
    entrypoint:
    - ./run.py
    - worker
    environment:
      APP_REDIS_HOST: redis
      APP_MEDIA_DIR: /media
      CHECK: worker
      RAVEN_DSN: ${RAVEN_DSN}
    restart: always
    depends_on:
    # currently doesn't use postgres
    - redis

  # TODO: https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3
