# App settings go here, they're validated in app.main.load_settings
dev:
  py_file: app/main.py
  static_path: static/
database:
  name: 'socket_server'
  user: 'postgres'  # TODO make sure connection settings here are correct
  password: 'You need to set this!'
  host: localhost
  port: 5432
# this is the key used to encrypt cookies. Keep it safe!
# you can generate a new key with `base64.urlsafe_b64encode(os.urandom(32))`
cookie_secret_key: 'iNLlUJcacSUUS4qQXyF4uX3hqaEbCuuDDDZHoBpZ3Pw='
