dev:
  py_file: app/main.py
  debug_toolbar: false
database:
  name: 'socket'
  user: 'postgres'
  password: null
  host: localhost
  port: 5432
redis:
  host: localhost
  port: 6379
  password: null
  database: 0
# secret used between socket and secure.tutorcruncher.com to sign webhooks and authenticate API requests
master_key: 'this is a secret'
root_url: https://socket.tutorcruncher.com
media_dir: ./media
media_url: https://socket.tutorcruncher.com/media
